      [build]
      command = "npm run build"
      publish = "dist" # ¡Cambia a 'dist' si tu bundler (ej. Vite) genera esta carpeta!
      functions = "netlify/functions"

    [functions]
      node_bundler = "esbuild"
     
    