    [build]
      publish = "Joel" # La carpeta donde Netlify encontrar치 tu index.html y otros archivos est치ticos
      functions = "netlify/functions" # La carpeta donde Netlify buscar치 tus funciones serverless

    [functions]
      node_bundler = "esbuild" # Se recomienda para funciones Node.js
      # A침adido: Timeout para funciones, si toman tiempo en arrancar o responder
      # timeout = 10 # segundos (por defecto es 10, puedes subirlo a 30 si tienes muchas operaciones)
    